Repository Qiskit/qiskit-aqua, pull requests merged in 2018-07, with the labels that each got.

#26 Fix/use list for paulis and update helper function of ising model
  qiskit_acqua/ising/maxcut.py
  qiskit_acqua/ising/partition.py
  qiskit_acqua/ising/stableset.py
Labels: bug

#27 F2 finite field functions and find_Z2_symmetries function
  qiskit_acqua/operator.py
Labels: enhancement

#29 multiclass svm (one against all)
  qiskit_acqua/multiclass/__init__.py
  qiskit_acqua/multiclass/data_preprocess.py
  qiskit_acqua/multiclass/dimension_reduction.py
  qiskit_acqua/multiclass/estimator.py
  qiskit_acqua/multiclass/one_against_rest.py
  qiskit_acqua/multiclass_classicalsvm/__init__.py
  qiskit_acqua/multiclass_classicalsvm/classical_svm_one_against_rest.py
  qiskit_acqua/multiclass_classicalsvm/linear_svc_estimator.py
  qiskit_acqua/multiclass_quantumsvm/__init__.py
  qiskit_acqua/multiclass_quantumsvm/qkernel_svm_estimator.py
  qiskit_acqua/multiclass_quantumsvm/quantum_svm_one_against_rest.py
  qiskit_acqua/svm/quantum_circuit_kernel.py
Labels: enhancement

#38 fix grover for cases that don't need ancillary qubits
  qiskit_acqua/grover/cnx.py
  qiskit_acqua/grover/grover.py
  qiskit_acqua/utils/oracles/sat.py
  test/test_grover.py
  test/test_grover_tiny.cnf
Labels: bug

#50 do not eliminate paulis with zero coefficient during addition
  qiskit_acqua/operator.py
  test/test_operator.py
Labels: enhancement

#49 Fix/max num circuits
  qiskit_acqua/operator.py
  qiskit_acqua/quantumalgorithm.py
  test/test_operator.py
Labels: bug

#54 Relax max circuits for simulation
  qiskit_acqua/operator.py
  qiskit_acqua/quantumalgorithm.py
Labels: bug, enhancement

#55 add summarize circuits
  qiskit_acqua/operator.py
  qiskit_acqua/quantumalgorithm.py
  qiskit_acqua/utils/__init__.py
  qiskit_acqua/utils/summarize_circuits.py
  qiskit_acqua/vqe/vqe.py
Labels: enhancement

#32 Ising model for TSP
  qiskit_acqua/ising/ising.py
  qiskit_acqua/ising/tsp.py
Labels: enhancement

#63 expose all execute setting in terra
  qiskit_aqua/parser/input_schema.json
  qiskit_aqua/quantumalgorithm.py
Labels: enhancement
