Repository Qiskit/qiskit-aqua, pull requests merged in 2018-10, with the labels that each got.

#119 update doc for backend
  docs/execution.rst
Labels: type: documentation

#152 validate parameter in init args
  qiskit_aqua/algorithms/adaptive/vqe/vqe.py
Labels: type: bug

#160 split the eval into multiple steps
  qiskit_aqua/operator.py
  qiskit_aqua/utils/run_circuits.py
Labels: type: enhancement

#167 Improve the speed of grouped paulis conversion with numpy
  qiskit_aqua/utils/pauligraph.py
Labels: type: enhancement

#166 improve the speed of operator
  qiskit_aqua/operator.py
Labels: type: enhancement

#171 fix the potential bug in qubit tapering and improve it with numpy
  qiskit_aqua/operator.py
Labels: type: bug

#175 support batch mode in QSVM variational and clean up VQE
  qiskit_aqua/algorithms/adaptive/qsvm/qsvm_variational.py
  qiskit_aqua/algorithms/adaptive/vqe/vqe.py
Labels: type: enhancement

#177 Enhance/operator
  qiskit_aqua/algorithms/adaptive/qsvm/qsvm_variational.py
  qiskit_aqua/algorithms/adaptive/vqe/vqe.py
  qiskit_aqua/algorithms/many_sample/qsvm/qsvm_kernel_binary.py
  qiskit_aqua/algorithms/single_sample/grover/grover.py
  qiskit_aqua/algorithms/single_sample/iqpe/iqpe.py
  qiskit_aqua/algorithms/single_sample/qpe/qpe.py
  qiskit_aqua/operator.py
  test/test_sat_oracle.py
Labels: type: enhancement

#179 bug fix in evaluating aux ops
  qiskit_aqua/algorithms/adaptive/vqe/vqe.py
Labels: type: bug
