Repository Qiskit/qiskit-aqua, pull requests merged in 2018-12, with the labels that each got.

#212 support passing the pass manager for programatic approach
  qiskit_aqua/_aqua.py
  qiskit_aqua/algorithms/many_sample/qsvm/qsvm_kernel.py
  qiskit_aqua/algorithms/quantumalgorithm.py
  test/test_eoh.py
  test/test_iqpe.py
  test/test_operator.py
  test/test_qpe.py
  test/test_vqe2iqpe.py
Labels: type: enhancement

#215 fix bugs to work with the newest Terra
  qiskit_aqua/algorithms/adaptive/vqe/vqe.py
  qiskit_aqua/algorithms/quantumalgorithm.py
  qiskit_aqua/operator.py
  qiskit_aqua/parser/input_schema.json
  qiskit_aqua/utils/run_circuits.py
  test/test_cnx.py
  test/test_evolution.py
Labels: type: bug

#218 parallelization support
  qiskit_aqua/algorithms/components/optimizers/cg.py
  qiskit_aqua/algorithms/components/optimizers/l_bfgs_b.py
  qiskit_aqua/algorithms/components/optimizers/optimizer.py
  qiskit_aqua/algorithms/components/optimizers/slsqp.py
  qiskit_aqua/algorithms/components/optimizers/tnc.py
  test/test_vqe.py
Labels: type: enhancement

#216 decouple quantum backend and quantum algorithm
  docs/execution.rst
  qiskit_aqua/__init__.py
  qiskit_aqua/_aqua.py
  qiskit_aqua/algorithms/adaptive/qsvm/cost_helpers.py
  qiskit_aqua/algorithms/adaptive/qsvm/qsvm_variational.py
  qiskit_aqua/algorithms/adaptive/vqe/vqe.py
  qiskit_aqua/algorithms/classical/cplex/cplex_ising.py
  qiskit_aqua/algorithms/classical/exacteigensolver/exacteigensolver.py
  qiskit_aqua/algorithms/classical/svm/svm_classical.py
  qiskit_aqua/algorithms/many_sample/eoh/eoh.py
  qiskit_aqua/algorithms/many_sample/qsvm/_qsvm_kernel_binary.py
  qiskit_aqua/algorithms/many_sample/qsvm/_qsvm_kernel_multiclass.py
  qiskit_aqua/algorithms/many_sample/qsvm/qsvm_kernel.py
  qiskit_aqua/algorithms/quantumalgorithm.py
  qiskit_aqua/algorithms/single_sample/grover/grover.py
  qiskit_aqua/algorithms/single_sample/iqpe/iqpe.py
  qiskit_aqua/algorithms/single_sample/qpe/qpe.py
  qiskit_aqua/operator.py
  qiskit_aqua/parser/input_schema.json
  qiskit_aqua/quantum_instance.py
  qiskit_aqua/utils/__init__.py
  qiskit_aqua/utils/run_circuits.py
  qiskit_aqua/utils/summarize_circuits.py
  test/test_eoh.py
  test/test_grover.py
  test/test_iqpe.py
  test/test_operator.py
  test/test_qaoa.py
  test/test_qpe.py
  test/test_qsvm_kernel.py
  test/test_qsvm_variational.py
  test/test_vqe.py
  test/test_vqe2iqpe.py
Labels: type: enhancement

#222 bug fix and add test for save and load model for QSVM
  qiskit_aqua/algorithms/adaptive/qsvm/qsvm_variational.py
  qiskit_aqua/algorithms/many_sample/qsvm/_qsvm_kernel_binary.py
  qiskit_aqua/algorithms/many_sample/qsvm/_qsvm_kernel_multiclass.py
  qiskit_aqua/algorithms/many_sample/qsvm/qsvm_kernel.py
  test/test_qsvm_kernel.py
  test/test_qsvm_variational.py
Labels: type: bug

#226 fix the qsvm tests in Linux
  qiskit_aqua/operator.py
  qiskit_aqua/utils/controlledcircuit.py
  qiskit_aqua/utils/dataset_helper.py
  test/test_iqpe.py
  test/test_qpe.py
  test/test_qsvm_kernel.py
  test/test_vqe.py
  test/test_vqe2iqpe.py
Labels: type: bug

#227 bug fix in find Z2 symmetries and add warning if skip_transpiler is used.
  qiskit_aqua/_aqua.py
  qiskit_aqua/operator.py
  test/test_cnx.py
  test/test_evolution.py
  test/test_sat_oracle.py
Labels: type: bug

#232 bug fix for the newest terra
  qiskit_aqua/algorithms/components/initial_states/custom.py
Labels: type: bug

#250 update docs for feature map
  docs/feature_maps.rst
Labels: type: documentation

#248 update doc for amplitude estimation and uncertainty problems
  docs/algorithms.rst
  docs/uncertainty_problem.rst
Labels: type: documentation

#255 proper approach to set max number of circuit per job
  qiskit_aqua/utils/run_circuits.py
  test/common.py
Labels: type: enhancement

#258 fix the potential issue if using Aer.
  qiskit_aqua/operator.py
  qiskit_aqua/utils/run_circuits.py
Labels: type: enhancement

#265 works with Aer internally
  .travis.yml
  qiskit_aqua/quantum_instance.py
  qiskit_aqua/utils/backend_utils.py
  qiskit_aqua/utils/run_circuits.py
  requirements-dev.txt
  requirements.txt
  setup.py
  test/test_qsvm_kernel.py
  test/test_qsvm_variational.py
Labels: type: enhancement
