Repository Qiskit/qiskit-aqua, pull requests merged in 2019-05, with the labels that each got.

#506 add measurement error mitigation
  CHANGELOG.rst
  qiskit/aqua/operator.py
  qiskit/aqua/parser/input_schema.json
  qiskit/aqua/qiskit_aqua.py
  qiskit/aqua/qiskit_aqua_globals.py
  qiskit/aqua/quantum_instance.py
  qiskit/aqua/utils/__init__.py
  qiskit/aqua/utils/measurement_error_mitigation.py
  qiskit/aqua/utils/run_circuits.py
  test/test_caching.py
  test/test_measure_error_mitigation.py
Labels: type: enhancement

#521 use seed simulator to control the randomness
  qiskit/aqua/qiskit_aqua.py
  qiskit/aqua/quantum_instance.py
  requirements-dev.txt
  requirements.txt
  setup.py
  test/test_measure_error_mitigation.py
  test/test_qsvm.py
  test/test_skip_qobj_validation.py
  test/test_vqc.py
  test/test_vqe.py
Labels: type: bug

#519 avoid for searching specific registers in the Operator class
  qiskit/aqua/algorithms/adaptive/vqe/vqe.py
  qiskit/aqua/operator.py
Labels: type: enhancement

#527 bug fixed in vqe since operator changes api
  qiskit/aqua/algorithms/adaptive/vqe/vqe.py
Labels: type: enhancement

#536 Adapt to Terra's new Qubit class
  qiskit/aqua/circuits/fourier_transform_circuits.py
  qiskit/aqua/circuits/gates/boolean_logical_gates.py
  qiskit/aqua/circuits/gates/controlled_hadamard_gate.py
  qiskit/aqua/circuits/gates/controlled_ry_gates.py
  qiskit/aqua/circuits/gates/multi_control_multi_target_gate.py
  qiskit/aqua/circuits/gates/multi_control_toffoli_gate.py
  qiskit/aqua/circuits/gates/multi_control_u1_gate.py
  qiskit/aqua/circuits/gates/multi_control_u3_gate.py
  qiskit/aqua/circuits/gates/relative_phase_toffoli.py
  qiskit/aqua/utils/circuit_utils.py
  qiskit/aqua/utils/controlled_circuit.py
  test/test_hhl.py
  test/test_simon.py
  test/test_vqc.py
Labels: status: on hold
