Repository Qiskit/qiskit-aqua, pull requests merged in 2019-08, with the labels that each got.

#634 Bug fix on new operator when same paulis are passed into constructor
  qiskit/aqua/algorithms/adaptive/vqe/vqe.py
  qiskit/aqua/operators/__init__.py
  qiskit/aqua/operators/common.py
  qiskit/aqua/operators/op_converter.py
  qiskit/aqua/operators/weighted_pauli_operator.py
  qiskit/chemistry/aqua_extensions/components/initial_states/hartree_fock.py
  test/aqua/operators/test_tpb_grouped_weigted_pauli_operator.py
  test/aqua/operators/test_weighted_pauli_operator.py
Labels: type: bug

#638 use assemble rather than assemble circuits
  qiskit/aqua/quantum_instance.py
  qiskit/aqua/utils/run_circuits.py
Labels: type: bug

#643 Fix the docstring
  qiskit/aqua/components/eigs/eigs_qpe.py
  qiskit/aqua/operators/matrix_operator.py
  qiskit/aqua/operators/op_converter.py
  qiskit/aqua/translators/ising/exact_cover.py
  qiskit/aqua/translators/ising/graph_partition.py
  qiskit/aqua/translators/ising/max_cut.py
  qiskit/aqua/translators/ising/portfolio_diversification.py
  qiskit/aqua/translators/ising/set_packing.py
  qiskit/aqua/translators/ising/stable_set.py
  qiskit/aqua/translators/ising/vehicle_routing.py
  qiskit/aqua/translators/ising/vertex_cover.py
  qiskit/aqua/utils/random_matrix_generator.py
  test/aqua/test_vqc.py
Labels: type: documentation

#646 bug fix, grouped pauli was not convert to matrix
  qiskit/aqua/operators/op_converter.py
Labels: type: bug

#653 In the declarative mode, pass backend object to parser before parsing
  qiskit/aqua/qiskit_aqua.py
Labels: type: bug

#655 Add qEom to study excited states of a molecule
  CHANGELOG.md
  qiskit/aqua/operators/op_converter.py
  qiskit/aqua/operators/weighted_pauli_operator.py
  qiskit/chemistry/aqua_extensions/algorithms/__init__.py
  qiskit/chemistry/aqua_extensions/algorithms/q_equation_of_motion/__init__.py
  qiskit/chemistry/aqua_extensions/algorithms/q_equation_of_motion/q_eom_ee.py
  qiskit/chemistry/aqua_extensions/algorithms/q_equation_of_motion/q_eom_vqe.py
  qiskit/chemistry/aqua_extensions/algorithms/q_equation_of_motion/q_equation_of_motion.py
  qiskit/chemistry/parser/substitutions.json
  test/chemistry/test_qeom_ee.py
  test/chemistry/test_qeom_vqe.py
Labels: type: enhancement
