Repository Qiskit/qiskit-aqua, pull requests merged in 2020-08, with the labels that each got.

#1154 VQE change backends Failure
  qiskit/aqua/algorithms/minimum_eigen_solvers/vqe.py
  releasenotes/notes/expectation_change_backend-5483d30095f8bd82.yaml
  test/aqua/test_vqe.py
  test/optimization/test_qaoa.py
Labels: Changelog: Bugfix

#1161 Mp2info incorrect when only one double excitation
  qiskit/chemistry/mp2info.py
  test/chemistry/test_mp2info.py
Labels: Changelog: Bugfix, stable backport potential

#1175 Restrict Ignis required version >= 0.4.0
  requirements.txt
  setup.py
Labels: stable backport potential

#1178 Properly deprecate quadratic program ising converter classes
  qiskit/aqua/operators/list_ops/summed_op.py
  qiskit/optimization/converters/__init__.py
  qiskit/optimization/converters/ising_to_quadratic_program.py
  qiskit/optimization/converters/quadratic_program_to_ising.py
  qiskit/optimization/problems/quadratic_program.py
  releasenotes/notes/deprecate-ising-converter-classes-11749cdb6ac1bfaa.yaml
  test/optimization/test_converters.py
Labels: Changelog: Deprecation, priority: high, stable backport potential

#1130 Direct appending circuits revised in uccsd for even better performance
  qiskit/chemistry/components/variational_forms/uccsd.py
Labels: Chemistry

#1187 Fix cyclicity check and add max_iterations in VQEAdapt
  qiskit/chemistry/algorithms/minimum_eigen_solvers/vqe_adapt.py
  releasenotes/notes/vqe-adapt-fixes-8c584ab000ab5f8c.yaml
  test/chemistry/test_vqe_uccsd_adapt.py
Labels: Changelog: Bugfix, Changelog: New Feature, Chemistry

#1203 Fix miniconda psi4 install error on github actions
  .github/actions/install-aqua/action.yml
  .github/actions/install-libraries/action.yml
  .github/actions/install-master-dependencies/action.yml
  .github/workflows/main.yml
Labels: priority: critical, type: bug

#1201 correct the UCCSD.compute_excitation_lists()
  qiskit/chemistry/components/variational_forms/uccsd.py
  releasenotes/notes/UCCSD-excitation-list-0fbb1af60f47192f.yaml
  test/chemistry/test_uccsd_hartree_fock.py
Labels: Changelog: Bugfix, stable backport potential

#1191 Update docstrings for optimization
  qiskit/optimization/algorithms/__init__.py
  qiskit/optimization/algorithms/optimization_algorithm.py
  qiskit/optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit/optimization/converters/__init__.py
  qiskit/optimization/converters/ising_to_quadratic_program.py
  qiskit/optimization/converters/quadratic_program_converter.py
  qiskit/optimization/converters/quadratic_program_to_ising.py
  qiskit/optimization/problems/__init__.py
  qiskit/optimization/problems/quadratic_program.py
Labels: type: documentation

#1202 Warm start ADMM
  qiskit/optimization/algorithms/admm_optimizer.py
  releasenotes/notes/admm-warm-start-6f5b5c801bcdf78f.yaml
  test/optimization/test_admm.py
Labels: Changelog: New Feature, Optimization, type: enhancement

#1194 Add a parameters method to the Operators
  qiskit/aqua/operators/list_ops/list_op.py
  qiskit/aqua/operators/operator_base.py
  qiskit/aqua/operators/primitive_ops/primitive_op.py
  qiskit/aqua/operators/state_fns/state_fn.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: New Feature

#1207 ComposedOp.eval shouldn't mutate the oplist
  qiskit/aqua/operators/list_ops/composed_op.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix, stable backport potential

#1031 Replace Optimizer.SupportLevel with OptimizerSupportLevel to support Sphinx > 3.1.0
  .pylintdict
  .travis.yml
  qiskit/aqua/components/optimizers/__init__.py
  qiskit/aqua/components/optimizers/adam_amsgrad.py
  qiskit/aqua/components/optimizers/aqgd.py
  qiskit/aqua/components/optimizers/cg.py
  qiskit/aqua/components/optimizers/cobyla.py
  qiskit/aqua/components/optimizers/gsls.py
  qiskit/aqua/components/optimizers/l_bfgs_b.py
  qiskit/aqua/components/optimizers/nelder_mead.py
  qiskit/aqua/components/optimizers/nft.py
  qiskit/aqua/components/optimizers/nlopts/nloptimizer.py
  qiskit/aqua/components/optimizers/optimizer.py
  qiskit/aqua/components/optimizers/p_bfgs.py
  qiskit/aqua/components/optimizers/powell.py
  qiskit/aqua/components/optimizers/slsqp.py
  qiskit/aqua/components/optimizers/spsa.py
  qiskit/aqua/components/optimizers/tnc.py
  releasenotes/notes/optimization-supportlevel-d18e8dbced7172e0.yaml
  requirements-dev.txt
Labels: type: documentation

#1210 Consistent behaviour of StateFn.eval with OperatorBase.eval
  qiskit/aqua/operators/operator_base.py
  qiskit/aqua/operators/primitive_ops/circuit_op.py
  qiskit/aqua/operators/primitive_ops/matrix_op.py
  qiskit/aqua/operators/primitive_ops/pauli_op.py
  qiskit/aqua/operators/primitive_ops/primitive_op.py
  qiskit/aqua/operators/state_fns/circuit_state_fn.py
  qiskit/aqua/operators/state_fns/dict_state_fn.py
  qiskit/aqua/operators/state_fns/operator_state_fn.py
  qiskit/aqua/operators/state_fns/state_fn.py
  qiskit/aqua/operators/state_fns/vector_state_fn.py
  releasenotes/notes/statefn-eval-51ecf38a7a3cc087.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: New Feature

#1216 Limit P_BFGS unit test to max. processes 4
  test/aqua/test_optimizers.py
Labels: type: bug
