Repository Qiskit/qiskit-aqua, pull requests merged in 2020-10, with the labels that each got.

#1268 Refactoring `Grover` class in `QuantumAlgorithm`
  .pylintdict
  qiskit/aqua/algorithms/amplitude_amplifiers/grover.py
  qiskit/aqua/utils/__init__.py
  qiskit/aqua/utils/name_unnamed_args.py
  qiskit/optimization/algorithms/grover_optimizer.py
  test/aqua/test_grover.py
Labels: Changelog: API Change

#1298 Ignore folders starting with . on check copyright tool
  tools/check_copyright.py
  tox.ini
Labels: type: bug

#1301 changed cryptic u gates to readable x and h
  qiskit/aqua/algorithms/minimum_eigen_solvers/iqpe.py
  qiskit/aqua/circuits/boolean_logical_circuits.py
  qiskit/aqua/circuits/phase_estimation_circuit.py
  qiskit/aqua/components/initial_states/custom.py
  qiskit/aqua/components/reciprocals/long_division.py
  qiskit/aqua/components/reciprocals/lookup_rotation.py
  qiskit/aqua/operators/legacy/common.py
  qiskit/aqua/utils/controlled_circuit.py
  qiskit/chemistry/components/initial_states/hartree_fock.py
  qiskit/chemistry/components/initial_states/vscf.py
  qiskit/chemistry/components/variational_forms/chc.py
  test/aqua/test_initial_state_custom.py
  test/chemistry/test_initial_state_hartree_fock.py
Labels: type: enhancement

#1280 Add seeds to CHC+VSCF tests
  test/chemistry/test_chc_vscf.py
  test/chemistry/test_uvcc_vscf.py
Labels: Chemistry

#1307 Deprecate the ``WeightedSumOperator``
  qiskit/aqua/circuits/weighted_sum_operator.py
  releasenotes/notes/deprecate-weighted-sum-op-9dc0eccac8e93963.yaml
  test/aqua/test_amplitude_estimation_circuitfactory.py
  test/aqua/test_weighted_sum_operator.py
Labels: Changelog: Deprecation

#1304 Fix Trotter evolution of sums with identity terms
  qiskit/aqua/operators/evolutions/pauli_trotter_evolution.py
  releasenotes/notes/fix-trotter-global-phase-eb86e17722b4d045.yaml
  test/aqua/operators/test_evolution.py
Labels: Changelog: Bugfix

#1270 Add support for v2 provider interface
  qiskit/aqua/algorithms/amplitude_amplifiers/grover.py
  qiskit/aqua/algorithms/amplitude_estimators/ae.py
  qiskit/aqua/algorithms/amplitude_estimators/ae_algorithm.py
  qiskit/aqua/algorithms/amplitude_estimators/iqae.py
  qiskit/aqua/algorithms/amplitude_estimators/mlae.py
  qiskit/aqua/algorithms/classifiers/qsvm/qsvm.py
  qiskit/aqua/algorithms/classifiers/vqc.py
  qiskit/aqua/algorithms/distribution_learners/qgan.py
  qiskit/aqua/algorithms/education/bernstein_vazirani.py
  qiskit/aqua/algorithms/education/deutsch_jozsa.py
  qiskit/aqua/algorithms/education/eoh.py
  qiskit/aqua/algorithms/education/simon.py
  qiskit/aqua/algorithms/factorizers/shor.py
  qiskit/aqua/algorithms/linear_solvers/hhl.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/iqpe.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/qaoa.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/qpe.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/aqua/algorithms/quantum_algorithm.py
  qiskit/aqua/algorithms/vq_algorithm.py
  qiskit/aqua/operators/converters/circuit_sampler.py
  qiskit/aqua/operators/expectations/expectation_factory.py
  qiskit/aqua/utils/run_circuits.py
  qiskit/chemistry/algorithms/eigen_solvers/q_eom_vqe.py
  qiskit/chemistry/algorithms/minimum_eigen_solvers/vqe_adapt.py
  qiskit/chemistry/applications/molecular_ground_state_energy.py
  qiskit/optimization/algorithms/grover_optimizer.py
Labels: Changelog: New Feature

#1312 Fix measurements bug when specifying `qasm_simulator` in `GroverOptimizer`
  qiskit/optimization/algorithms/grover_optimizer.py
  test/optimization/test_grover_optimizer.py
Labels: Changelog: Bugfix

#1310 Handle infeasible filter criterion for NumPy(Minimum)Eigensolver and MinimumEigenOptimizer
  qiskit/aqua/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/optimization/algorithms/minimum_eigen_optimizer.py
  qiskit/optimization/algorithms/optimization_algorithm.py
  qiskit/optimization/converters/inequality_to_equality.py
  qiskit/optimization/converters/integer_to_binary.py
  qiskit/optimization/converters/linear_equality_to_penalty.py
  test/aqua/test_numpy_eigen_solver.py
  test/aqua/test_numpy_minimum_eigen_solver.py
  test/optimization/test_min_eigen_optimizer.py
Labels: Changelog: New Feature

#1297 [WIP] Refactor Chemistry Drivers to also accept Molecule class
  qiskit/chemistry/applications/molecular_ground_state_energy.py
  qiskit/chemistry/drivers/__init__.py
  qiskit/chemistry/drivers/base_driver.py
  qiskit/chemistry/drivers/fcidumpd/fcidumpdriver.py
  qiskit/chemistry/drivers/fermionic_driver.py
  qiskit/chemistry/drivers/gaussiand/gaussian_log_driver.py
  qiskit/chemistry/drivers/gaussiand/gaussiandriver.py
  qiskit/chemistry/drivers/hdf5d/hdf5driver.py
  qiskit/chemistry/drivers/molecule.py
  qiskit/chemistry/drivers/psi4d/psi4driver.py
  qiskit/chemistry/drivers/pyquanted/pyquantedriver.py
  qiskit/chemistry/drivers/pyscfd/pyscfdriver.py
  qiskit/chemistry/drivers/units_type.py
  test/chemistry/test_driver.py
  test/chemistry/test_driver_gaussian.py
  test/chemistry/test_driver_molecule.py
  test/chemistry/test_driver_psi4.py
  test/chemistry/test_driver_pyquante.py
  test/chemistry/test_driver_pyscf.py
Labels: Changelog: API Change, Chemistry

#1341 Make QGAN run primarily on circuits
  qiskit/aqua/components/neural_networks/generative_network.py
  qiskit/aqua/components/neural_networks/quantum_generator.py
  releasenotes/notes/qgan-on-circuits-9bd57bd707b31897.yaml
  test/aqua/test_qgan.py
Labels: Changelog: Deprecation, Changelog: New Feature

#1342 Finance applications
  .pylintdict
  .pylintrc
  README.md
  qiskit/finance/applications/__init__.py
  qiskit/finance/applications/european_call_delta.py
  qiskit/finance/applications/european_call_expected_value.py
  qiskit/finance/applications/fixed_income_expected_value.py
  qiskit/finance/applications/gaussian_conditional_independence_model.py
  releasenotes/notes/finance-circuits-f39c12637226efd9.yaml
  test/finance/test_european_call_delta.py
  test/finance/test_european_call_expected_value.py
  test/finance/test_fixed_income_expected_value.py
  test/finance/test_readme_sample.py
Labels: Changelog: New Feature

#1348 Deprecate the ``CircuitFactory`` and derived types
  qiskit/aqua/algorithms/amplitude_estimators/ae.py
  qiskit/aqua/algorithms/amplitude_estimators/ae_algorithm.py
  qiskit/aqua/algorithms/amplitude_estimators/iqae.py
  qiskit/aqua/algorithms/amplitude_estimators/mlae.py
  qiskit/aqua/components/uncertainty_models/bernoulli_distribution.py
  qiskit/aqua/components/uncertainty_models/gaussian_conditional_independence_model.py
  qiskit/aqua/components/uncertainty_models/log_normal_distribution.py
  qiskit/aqua/components/uncertainty_models/multivariate_distribution.py
  qiskit/aqua/components/uncertainty_models/multivariate_log_normal_distribution.py
  qiskit/aqua/components/uncertainty_models/multivariate_normal_distribution.py
  qiskit/aqua/components/uncertainty_models/multivariate_uniform_distribution.py
  qiskit/aqua/components/uncertainty_models/multivariate_variational_distribution.py
  qiskit/aqua/components/uncertainty_models/normal_distribution.py
  qiskit/aqua/components/uncertainty_models/uncertainty_model.py
  qiskit/aqua/components/uncertainty_models/uniform_distribution.py
  qiskit/aqua/components/uncertainty_models/univariate_distribution.py
  qiskit/aqua/components/uncertainty_models/univariate_variational_distribution.py
  qiskit/aqua/components/uncertainty_problems/uncertainty_problem.py
  qiskit/aqua/components/uncertainty_problems/univariate_piecewise_linear_objective.py
  qiskit/aqua/utils/circuit_factory.py
  releasenotes/notes/deprecate-circuit-factories-3b9d85d07c07795b.yaml
  test/aqua/test_amplitude_estimation_circuitfactory.py
  test/finance/test_amplitude_estimation.py
Labels: Changelog: Deprecation

#1351 Change base gate U3 to U
  qiskit/aqua/quantum_instance.py
  qiskit/aqua/utils/circuit_utils.py
  qiskit/aqua/utils/controlled_circuit.py
Labels: Changelog: Bugfix

#1345 Opflow Cvar Implementation
  .pylintdict
  qiskit/aqua/components/optimizers/spsa.py
  qiskit/aqua/operators/__init__.py
  qiskit/aqua/operators/expectations/__init__.py
  qiskit/aqua/operators/expectations/cvar_expectation.py
  qiskit/aqua/operators/state_fns/__init__.py
  qiskit/aqua/operators/state_fns/cvar_measurement.py
  releasenotes/notes/cvar-expectation-bbc2ccff95132b35.yaml
  test/aqua/operators/test_cvar.py
Labels: Changelog: New Feature

#1253 Implement selection of optimizer in the QGAN algorithm
  qiskit/aqua/algorithms/distribution_learners/qgan.py
  qiskit/aqua/components/neural_networks/quantum_generator.py
  test/aqua/test_qgan.py
Labels: Changelog: New Feature

#1344 Setting is_measurement for converted state functions and backend arg required to CircuitSampler
  qiskit/aqua/operators/converters/circuit_sampler.py
  releasenotes/notes/fix-is-measurements-in-circuit-sampler-18679ad9bfe3f9cb.yaml
  test/aqua/operators/test_state_op_meas_evals.py
Labels: Changelog: Bugfix

#1293 Gradients Framework
  .github/workflows/main.yml
  .pylintdict
  docs/apidocs/qiskit.aqua.operators.gradients.rst
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/qaoa.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/aqua/algorithms/vq_algorithm.py
  qiskit/aqua/operators/__init__.py
  qiskit/aqua/operators/gradients/__init__.py
  qiskit/aqua/operators/gradients/circuit_gradients/__init__.py
  qiskit/aqua/operators/gradients/circuit_gradients/circuit_gradient.py
  qiskit/aqua/operators/gradients/circuit_gradients/lin_comb.py
  qiskit/aqua/operators/gradients/circuit_gradients/param_shift.py
  qiskit/aqua/operators/gradients/circuit_qfis/__init__.py
  qiskit/aqua/operators/gradients/circuit_qfis/circuit_qfi.py
  qiskit/aqua/operators/gradients/circuit_qfis/lin_comb_full.py
  qiskit/aqua/operators/gradients/circuit_qfis/overlap_block_diag.py
  qiskit/aqua/operators/gradients/circuit_qfis/overlap_diag.py
  qiskit/aqua/operators/gradients/derivative_base.py
  qiskit/aqua/operators/gradients/gradient.py
  qiskit/aqua/operators/gradients/gradient_base.py
  qiskit/aqua/operators/gradients/hessian.py
  qiskit/aqua/operators/gradients/hessian_base.py
  qiskit/aqua/operators/gradients/natural_gradient.py
  qiskit/aqua/operators/gradients/qfi.py
  qiskit/aqua/operators/gradients/qfi_base.py
  qiskit/aqua/operators/list_ops/list_op.py
  releasenotes/notes/gradient_framework-df374d2929089bf1.yaml
  test/aqua/operators/test_gradients.py
Labels: Changelog: API Change, Changelog: New Feature

#1355 Orbital Optimization VQE algorithm for Chemistry
  .pylintdict
  qiskit/chemistry/algorithms/ground_state_solvers/__init__.py
  qiskit/chemistry/algorithms/ground_state_solvers/adapt_vqe.py
  qiskit/chemistry/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit/chemistry/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit/chemistry/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uccsd_factory.py
  qiskit/chemistry/algorithms/ground_state_solvers/orbital_optimization_vqe.py
  qiskit/chemistry/drivers/fcidumpd/fcidumpdriver.py
  qiskit/chemistry/drivers/hdf5d/hdf5driver.py
  qiskit/chemistry/results/__init__.py
  releasenotes/notes/oovqe-e8ff4f50f30687c3.yaml
  test/chemistry/test_oovqe.py
  test/chemistry/test_oovqe_h4.hdf5
  test/chemistry/test_oovqe_h4_uhf.hdf5
  test/chemistry/test_oovqe_lih.hdf5
  test/chemistry/test_vqe_uccsd_mes_factory.py
Labels: Changelog: New Feature, Chemistry

#1352 BOPES Sampler algorithm for Chemistry
  .pylintdict
  qiskit/chemistry/algorithms/pes_samplers/__init__.py
  qiskit/chemistry/algorithms/pes_samplers/bopes_sampler.py
  qiskit/chemistry/algorithms/pes_samplers/extrapolator.py
  qiskit/chemistry/algorithms/pes_samplers/potentials/energy_surface_spline.py
  qiskit/chemistry/algorithms/pes_samplers/potentials/harmonic_potential.py
  qiskit/chemistry/algorithms/pes_samplers/potentials/morse_potential.py
  qiskit/chemistry/algorithms/pes_samplers/potentials/potential_base.py
  qiskit/chemistry/constants.py
  qiskit/chemistry/results/bopes_sampler_result.py
  test/chemistry/test_bopes_sampler.py
  test/chemistry/test_data_potentials.py
  test/chemistry/test_extrapolators.py
  test/chemistry/test_potential.py
Labels: Changelog: New Feature, Chemistry

#1354 Excited States algorithms and support for Chemistry
  .pylintdict
  qiskit/aqua/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/aqua/operators/legacy/common.py
  qiskit/chemistry/algorithms/excited_states_solvers/__init__.py
  qiskit/chemistry/algorithms/excited_states_solvers/eigensolver_factories/__init__.py
  qiskit/chemistry/algorithms/excited_states_solvers/eigensolver_factories/eigensolver_factory.py
  qiskit/chemistry/algorithms/excited_states_solvers/eigensolver_factories/numpy_eigensolver_factory.py
  qiskit/chemistry/algorithms/excited_states_solvers/excited_states_eigensolver.py
  qiskit/chemistry/algorithms/excited_states_solvers/excited_states_solver.py
  qiskit/chemistry/algorithms/excited_states_solvers/qeom.py
  qiskit/chemistry/algorithms/ground_state_solvers/adapt_vqe.py
  qiskit/chemistry/algorithms/ground_state_solvers/ground_state_eigensolver.py
  qiskit/chemistry/algorithms/ground_state_solvers/ground_state_solver.py
  qiskit/chemistry/algorithms/pes_samplers/bopes_sampler.py
  qiskit/chemistry/results/electronic_structure_result.py
  qiskit/chemistry/transformations/fermionic_transformation.py
  qiskit/chemistry/transformations/transformation.py
  releasenotes/notes/excited-states-interface-a7ac8ae621b35daa.yaml
  releasenotes/notes/ground_state_interface-42576cb6658a46e0.yaml
  test/chemistry/test_adapt_vqe.py
  test/chemistry/test_bopes_sampler.py
  test/chemistry/test_driver_methods_gsc.py
  test/chemistry/test_excited_states_solvers.py
  test/chemistry/test_groundstate_eigensolver.py
  test/chemistry/test_swaprz.py
  test/chemistry/test_symmetries.py
  test/chemistry/test_uccsd_advanced.py
  test/chemistry/test_uccsd_hartree_fock.py
Labels: Changelog: New Feature

#1380 Message enhancement in MatrixOp init
  qiskit/aqua/algorithms/quantum_algorithm.py
  qiskit/aqua/operators/primitive_ops/circuit_op.py
  qiskit/aqua/operators/primitive_ops/matrix_op.py
  qiskit/aqua/operators/primitive_ops/pauli_op.py
  qiskit/aqua/operators/primitive_ops/primitive_op.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix

#1379 Fixes #1371 - Adds slice support for ListOp
  qiskit/aqua/operators/list_ops/list_op.py
  releasenotes/notes/slice-support-ListOp-ea586438661d2ca9.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: New Feature

#1362 Don't add Hadamards to a user-defined initial state in QAOA
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/var_form.py
  releasenotes/notes/qaoa-initial-state-bugfix-a92b38b805f36209.yaml
  test/optimization/test_qaoa.py
Labels: Changelog: Bugfix

#1382 Use PassManager in QuantumInstance transpile
  qiskit/aqua/quantum_instance.py
  releasenotes/notes/pass_manager-c5e934ffc31addb0.yaml
  test/aqua/test_bernstein_vazirani.py
Labels: Changelog: Bugfix

#1384 Allow Noise Simulation for simulator backends
  qiskit/aqua/quantum_instance.py
  releasenotes/notes/noise_model-8e27eb648456f8a9.yaml
  test/aqua/test_skip_qobj_validation.py
Labels: Changelog: Bugfix, stable backport potential

#1378 QSVM L2 Reg. introduction for convergence and over-fitting issue
  qiskit/aqua/algorithms/classifiers/qsvm/_qsvm_binary.py
  qiskit/aqua/algorithms/classifiers/qsvm/qsvm.py
  qiskit/aqua/utils/qp_solver.py
  releasenotes/notes/QSVM-L2-Norm-3382893ecafee124.yaml
  test/aqua/test_qsvm.py
Labels: Changelog: Bugfix, stable backport potential

#1391 qGAN - PyTorch Discriminator Fix
  qiskit/aqua/components/neural_networks/pytorch_discriminator.py
Labels: Changelog: Bugfix, stable backport potential

#1393 Fix for Incorrect translation of integer variables in ADMMOptimizer
  qiskit/optimization/algorithms/admm_optimizer.py
  test/optimization/test_admm.py
Labels: Changelog: Bugfix, stable backport potential

#1396 Failure on PSI4 CI
  .github/actions/install-libraries/action.yml
  .github/actions/install-master-dependencies/action.yml
  .github/workflows/main.yml
Labels: stable backport potential, type: bug

#1374 Replace the InitialState components by circuits
  README.md
  qiskit/aqua/algorithms/education/eoh.py
  qiskit/aqua/algorithms/linear_solvers/hhl.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/iqpe.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/qaoa.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/var_form.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/qpe.py
  qiskit/aqua/circuits/phase_estimation_circuit.py
  qiskit/aqua/components/initial_states/custom.py
  qiskit/aqua/components/initial_states/initial_state.py
  qiskit/aqua/components/initial_states/var_form_based.py
  qiskit/aqua/components/initial_states/zero.py
  qiskit/aqua/operators/legacy/weighted_pauli_operator.py
  qiskit/chemistry/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uccsd_factory.py
  qiskit/chemistry/applications/molecular_ground_state_energy.py
  qiskit/chemistry/circuit/library/__init__.py
  qiskit/chemistry/circuit/library/initial_states/__init__.py
  qiskit/chemistry/circuit/library/initial_states/hartree_fock.py
  qiskit/chemistry/circuit/library/initial_states/vscf.py
  qiskit/chemistry/components/initial_states/hartree_fock.py
  qiskit/chemistry/components/initial_states/vscf.py
  qiskit/chemistry/components/variational_forms/chc.py
  qiskit/chemistry/components/variational_forms/uccsd.py
  qiskit/chemistry/components/variational_forms/uvcc.py
  qiskit/chemistry/core/hamiltonian.py
  qiskit/chemistry/transformations/fermionic_transformation.py
  releasenotes/notes/deprecate-initial-states-61cd9f2842971ccb.yaml
  test/aqua/test_eoh.py
  test/aqua/test_hhl.py
  test/aqua/test_initial_state_custom.py
  test/aqua/test_initial_state_zero.py
  test/aqua/test_iqpe.py
  test/aqua/test_vqe2iqpe.py
  test/chemistry/circuit/library/test_hartree_fock.py
  test/chemistry/circuit/library/test_vscf.py
  test/chemistry/test_adapt_vqe.py
  test/chemistry/test_app_mgse.py
  test/chemistry/test_bopes_sampler.py
  test/chemistry/test_chc_vscf.py
  test/chemistry/test_core_hamiltonian.py
  test/chemistry/test_core_hamiltonian_orb_reduce.py
  test/chemistry/test_end2end_with_iqpe.py
  test/chemistry/test_end2end_with_qpe.py
  test/chemistry/test_fermionic_transformation.py
  test/chemistry/test_fermionic_transformation_orb_reduce.py
  test/chemistry/test_initial_state_hartree_fock.py
  test/chemistry/test_initial_state_vscf.py
  test/chemistry/test_qeom_vqe.py
  test/chemistry/test_readme_sample.py
  test/chemistry/test_swaprz.py
  test/chemistry/test_symmetries.py
  test/chemistry/test_uccsd_advanced.py
  test/chemistry/test_uccsd_hartree_fock.py
  test/chemistry/test_uvcc_vscf.py
  test/chemistry/test_vqe_uccsd_adapt.py
Labels: Changelog: Deprecation, Changelog: New Feature
