Repository Qiskit/qiskit-aqua, pull requests merged in 2020-09, with the labels that each got.

#1227 Drop support for Python 3.5
  .github/workflows/main.yml
  releasenotes/notes/drop-py35-a1036a3d38f3d79a.yaml
  requirements-dev.txt
  setup.py
  tox.ini
Labels: Changelog: Removal

#1228 Fix a bug of StateFn.traverse
  qiskit/aqua/operators/list_ops/list_op.py
  qiskit/aqua/operators/state_fns/state_fn.py
Labels: Changelog: Bugfix

#1235 Fix a bug of CircuitSampler
  qiskit/aqua/operators/converters/circuit_sampler.py
  test/aqua/operators/test_aer_pauli_expectation.py
Labels: Changelog: Bugfix

#1219 Add Grover and QAE result classes
  README.md
  qiskit/aqua/algorithms/__init__.py
  qiskit/aqua/algorithms/amplitude_amplifiers/__init__.py
  qiskit/aqua/algorithms/amplitude_amplifiers/grover.py
  qiskit/aqua/algorithms/amplitude_estimators/__init__.py
  qiskit/aqua/algorithms/amplitude_estimators/ae.py
  qiskit/aqua/algorithms/amplitude_estimators/ae_algorithm.py
  qiskit/aqua/algorithms/amplitude_estimators/iqae.py
  qiskit/aqua/algorithms/amplitude_estimators/mlae.py
  qiskit/aqua/algorithms/eigen_solvers/eigen_solver_result.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/aqua/algorithms/quantum_algorithm.py
  releasenotes/notes/grover-qae-result-ca0764a8f755e4d0.yaml
  test/aqua/test_amplitude_estimation.py
  test/aqua/test_custom_circuit_oracle.py
  test/aqua/test_grover.py
  test/aqua/test_measure_error_mitigation.py
  test/aqua/test_readme_sample.py
  test/finance/test_amplitude_estimation.py
  test/finance/test_european_call_expected_value.py
  test/finance/test_readme_sample.py
Labels: Changelog: API Change

#1199 Add feasibility checks to optimizers/converters
  qiskit/optimization/algorithms/admm_optimizer.py
  qiskit/optimization/algorithms/cplex_optimizer.py
  qiskit/optimization/algorithms/grover_optimizer.py
  qiskit/optimization/algorithms/minimum_eigen_optimizer.py
  qiskit/optimization/algorithms/multistart_optimizer.py
  qiskit/optimization/algorithms/optimization_algorithm.py
  qiskit/optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit/optimization/algorithms/slsqp_optimizer.py
  qiskit/optimization/converters/inequality_to_equality.py
  qiskit/optimization/converters/integer_to_binary.py
  qiskit/optimization/converters/linear_equality_to_penalty.py
  qiskit/optimization/problems/quadratic_program.py
  releasenotes/notes/feasibility-check-b99605f771e745b7.yaml
  test/optimization/test_converters.py
  test/optimization/test_quadratic_program.py
Labels: Changelog: API Change, Optimization, type: enhancement

#1224 Use Operator rather than unitary simulator to convert circuit to unitary matrix
  qiskit/aqua/operators/primitive_ops/circuit_op.py
  qiskit/aqua/operators/primitive_ops/pauli_op.py
  releasenotes/notes/pauli-expi-c0c97395190622c0.yaml
  test/aqua/operators/test_evolution.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix

#1242 Fix num oracle queries in QAE
  qiskit/aqua/algorithms/amplitude_estimators/ae.py
  releasenotes/notes/ae-num-oracle-queries-a14bd74321768de3.yaml
Labels: Changelog: Bugfix

#1234 Refactor QAE using the Grover operator
  .pylintdict
  .pylintrc
  qiskit/aqua/algorithms/amplitude_estimators/ae.py
  qiskit/aqua/algorithms/amplitude_estimators/ae_algorithm.py
  qiskit/aqua/algorithms/amplitude_estimators/iqae.py
  qiskit/aqua/algorithms/amplitude_estimators/mlae.py
  qiskit/aqua/circuits/phase_estimation_circuit.py
  releasenotes/notes/ae-on-circuit-ea1d914f91c571d2.yaml
  test/aqua/test_amplitude_estimation.py
  test/aqua/test_amplitude_estimation_circuitfactory.py
  test/finance/test_amplitude_estimation.py
Labels: Changelog: API Change

#1254 HHL and NumPyLSsolver Result Classes
  .pylintdict
  qiskit/aqua/algorithms/__init__.py
  qiskit/aqua/algorithms/amplitude_estimators/__init__.py
  qiskit/aqua/algorithms/linear_solvers/__init__.py
  qiskit/aqua/algorithms/linear_solvers/hhl.py
  qiskit/aqua/algorithms/linear_solvers/linear_solver_result.py
  qiskit/aqua/algorithms/linear_solvers/numpy_ls_solver.py
  releasenotes/notes/ls-result-31d50f1cad95792b.yaml
  test/aqua/test_hhl.py
  test/aqua/test_numpy_ls_solver.py
Labels: Changelog: New Feature

#1256 Fix a bug of the integer to binary converter
  qiskit/optimization/converters/integer_to_binary.py
  qiskit/optimization/problems/quadratic_expression.py
  test/optimization/test_converters.py
Labels: Changelog: Bugfix

#1252 Enhanced Aqgd optimizer
  qiskit/aqua/components/optimizers/aqgd.py
  releasenotes/notes/aqgd-epochs-8e6ad87971e8e2db.yaml
  test/aqua/test_optimizer_aqqd.py
Labels: Changelog: New Feature

#1144 Operator.compose should allow indices
  qiskit/aqua/operators/evolutions/evolved_op.py
  qiskit/aqua/operators/list_ops/composed_op.py
  qiskit/aqua/operators/list_ops/list_op.py
  qiskit/aqua/operators/list_ops/tensored_op.py
  qiskit/aqua/operators/operator_base.py
  qiskit/aqua/operators/primitive_ops/circuit_op.py
  qiskit/aqua/operators/primitive_ops/matrix_op.py
  qiskit/aqua/operators/primitive_ops/pauli_op.py
  qiskit/aqua/operators/primitive_ops/primitive_op.py
  qiskit/aqua/operators/state_fns/circuit_state_fn.py
  qiskit/aqua/operators/state_fns/dict_state_fn.py
  qiskit/aqua/operators/state_fns/operator_state_fn.py
  qiskit/aqua/operators/state_fns/state_fn.py
  qiskit/aqua/operators/state_fns/vector_state_fn.py
  qiskit/aqua/utils/arithmetic.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: New Feature

#1232 Vibrational structure calculations
  .pylintdict
  qiskit/chemistry/__init__.py
  qiskit/chemistry/bosonic_operator.py
  qiskit/chemistry/components/initial_states/__init__.py
  qiskit/chemistry/components/initial_states/vscf.py
  qiskit/chemistry/components/variational_forms/__init__.py
  qiskit/chemistry/components/variational_forms/chc.py
  qiskit/chemistry/components/variational_forms/uvcc.py
  qiskit/chemistry/drivers/__init__.py
  qiskit/chemistry/drivers/gaussiand/__init__.py
  qiskit/chemistry/drivers/gaussiand/gaussian_log_driver.py
  qiskit/chemistry/drivers/gaussiand/gaussian_log_result.py
  test/chemistry/CO2_freq_B3LYP_ccpVDZ.log
  test/chemistry/test_bosonic_operator.py
  test/chemistry/test_chc_vscf.py
  test/chemistry/test_driver_gaussian_log.py
  test/chemistry/test_driver_gaussian_log.txt
  test/chemistry/test_harmonic_integrals.py
  test/chemistry/test_initial_state_vscf.py
  test/chemistry/test_uvcc_vscf.py
Labels: Changelog: New Feature, Chemistry

#1240 Optimizers for noisy quantum devices (scikit-quant)
  .github/workflows/main.yml
  .pylintdict
  qiskit/aqua/components/optimizers/__init__.py
  qiskit/aqua/components/optimizers/bobyqa.py
  qiskit/aqua/components/optimizers/imfil.py
  qiskit/aqua/components/optimizers/snobfit.py
  requirements-dev.txt
  setup.py
  test/aqua/test_optimizers_scikitquant.py
Labels: Changelog: New Feature

#1259 Fixed bugs of converters in the case of that the range of variable is 0
  qiskit/optimization/converters/inequality_to_equality.py
  test/optimization/test_converters.py
Labels: Changelog: Bugfix

#1277 Create Eigensolver interface
  qiskit/aqua/algorithms/__init__.py
  qiskit/aqua/algorithms/eigen_solvers/__init__.py
  qiskit/aqua/algorithms/eigen_solvers/eigen_solver.py
  qiskit/aqua/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/aqua/aqua_globals.py
  releasenotes/notes/eingensolver-7adb5d4632706259.yaml
Labels: Changelog: New Feature
