Repository Qiskit/qiskit-aqua, pull requests merged in 2020-05, with the labels that each got.

#952 Remove the CPLEX requirement + Python 3.5 compatibility
  .pylintdict
  .travis.yml
  CHANGELOG.md
  qiskit/optimization/algorithms/admm_optimizer.py
  qiskit/optimization/algorithms/cplex_optimizer.py
  qiskit/optimization/converters/inequality_to_equality.py
  qiskit/optimization/converters/integer_to_binary.py
  qiskit/optimization/problems/quadratic_program.py
  requirements.txt
  setup.py
  test/optimization/test_admm.py
  test/optimization/test_converters.py
Labels: priority: high

#976 Fix recursive optimization
  qiskit/optimization/algorithms/minimum_eigen_optimizer.py
  qiskit/optimization/algorithms/recursive_minimum_eigen_optimizer.py
Labels: Optimization

#999 Fix cobyla optimizer
  qiskit/optimization/algorithms/cobyla_optimizer.py
  test/optimization/test_cobyla_optimizer.py
Labels: Changelog: Bugfix

#1000 Separate simplification of operators from SummedOp.add and fix bugs of add
  qiskit/aqua/components/optimizers/aqgd.py
  qiskit/aqua/operators/converters/abelian_grouper.py
  qiskit/aqua/operators/list_ops/list_op.py
  qiskit/aqua/operators/list_ops/summed_op.py
  qiskit/chemistry/drivers/fcidumpd/dumper.py
  qiskit/chemistry/drivers/fcidumpd/fcidumpdriver.py
  qiskit/optimization/converters/quadratic_program_to_qubo.py
  test/aqua/operators/test_abelian_grouper.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix

#1005 Allow Custom Lambda for Iterative Grover, see #893
  .pylintdict
  qiskit/aqua/algorithms/amplitude_amplifiers/grover.py
  test/aqua/test_grover.py
Labels: Changelog: New Feature

#1016 Fix ADAM resuseability
  qiskit/aqua/components/optimizers/adam_amsgrad.py
Labels: Changelog: Bugfix
