Repository Qiskit/qiskit-aqua, pull requests merged in 2020-06, with the labels that each got.

#1035 Remove cvxopt and use cvxpy instead
  .travis.yml
  qiskit/aqua/utils/qp_solver.py
  setup.py
  test/aqua/test_qsvm.py
Labels: stable backport potential

#1040 VQE default expectation selection
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/qaoa.py
  qiskit/aqua/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/aqua/operators/expectations/expectation_factory.py
  releasenotes/notes/vqe-expectation-122827ff3761537a.yaml
  test/aqua/test_vqe.py
Labels: stable backport potential

#1048 CircuitOp uses QuantumCircuit.compose, not .combine
  qiskit/aqua/operators/primitive_ops/circuit_op.py
  releasenotes/notes/circuit-op-compose-register-indep-5f3fd76dbb75c84e.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix, stable backport potential

#1045 Evaluate eigenvalues in MinEigenOptimizer more efficiently
  qiskit/optimization/algorithms/minimum_eigen_optimizer.py
Labels: type: enhancement

#1049 MatrixOp.to_instruction updated to return an Instruction
  qiskit/aqua/operators/primitive_ops/matrix_op.py
  releasenotes/notes/matrix-op-to-instruction-a990ec3a3db8ca8d.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix

#1055 Make cvxpy an optional dependency
  .pylintdict
  .travis.yml
  qiskit/aqua/utils/qp_solver.py
  releasenotes/notes/cvx-optional-e44920f87cff5e8d.yaml
  setup.py
Labels: stable backport potential

#1077 Correct coefficient propagation in the operators
  qiskit/aqua/operators/converters/circuit_sampler.py
  qiskit/aqua/operators/list_ops/composed_op.py
  qiskit/aqua/operators/state_fns/operator_state_fn.py
  releasenotes/notes/operator-coeff-eval-95efb26e95f6421a.yaml
  test/aqua/operators/test_pauli_expectation.py
  test/aqua/operators/test_state_op_meas_evals.py
Labels: Changelog: Bugfix, stable backport potential

#1075 Z2 symmetry fix for when no symmetries found
  qiskit/chemistry/core/hamiltonian.py
  test/chemistry/test_app_mgse.py
Labels: Changelog: Bugfix, stable backport potential

#1083 Set qcp to True for cvxpy Problem.solve in qp_solver
  qiskit/aqua/utils/qp_solver.py
Labels: stable backport potential
