Repository Qiskit/qiskit-aqua, pull requests merged in 2020-11, with the labels that each got.

#1400 Add job result accumulated time_taken to QuantumInstance
  qiskit/aqua/quantum_instance.py
  qiskit/aqua/utils/run_circuits.py
  releasenotes/notes/time_taken-51921da97ca3c13a.yaml
  test/aqua/test_amplitude_estimation.py
  test/aqua/test_measure_error_mitigation.py
  test/aqua/test_skip_qobj_validation.py
Labels: Changelog: New Feature

#1410 Fix ``seed_simulator=0`` in the quantum instance
  qiskit/aqua/quantum_instance.py
  releasenotes/notes/qi-seed-simulator-757f88ec183082f7.yaml
  test/aqua/operators/legacy/test_tpb_grouped_weighted_pauli_operator.py
  test/aqua/operators/legacy/test_weighted_pauli_operator.py
Labels: Changelog: Bugfix

#1414 Fix NLOpt optimizers trying to iterate NoneType
  qiskit/aqua/components/optimizers/nlopts/nloptimizer.py
  test/aqua/test_nlopt_optimizers.py
Labels: Changelog: Bugfix

#1411 Fix the hashable issue of PrimitiveOp
  qiskit/aqua/operators/list_ops/summed_op.py
  qiskit/aqua/operators/primitive_ops/primitive_op.py
  releasenotes/notes/fix_hashable-0ccf249a2c19fc0e.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: API Change, Changelog: Bugfix, Changelog: Deprecation

#1420 DOCplex has removed one_letter_symbol() from VarType causing problems in Aqua optimization module
  qiskit/optimization/problems/quadratic_program.py
  releasenotes/notes/docplex-fix-e401d4b511ca5244.yaml
Labels: Changelog: Bugfix, stable backport potential

#1424 QAOA should generate random initial points if they are None
  qiskit/aqua/algorithms/minimum_eigen_solvers/qaoa/var_form.py
  test/finance/test_portfolio.py
  test/optimization/test_qaoa.py
Labels: Changelog: Bugfix, stable backport potential

#1373 CVaRExpectation variance calculation
  .pylintdict
  qiskit/aqua/operators/expectations/cvar_expectation.py
  qiskit/aqua/operators/state_fns/cvar_measurement.py
  test/aqua/operators/test_cvar.py
Labels: Changelog: Bugfix

#1423 Fixes AQGD when an integer value is passed as eta or momentum
  qiskit/aqua/components/optimizers/aqgd.py
  releasenotes/notes/aqgd-int-values-fix-9d9c74381802be18.yaml
  test/aqua/test_optimizer_aqgd.py
Labels: Changelog: Bugfix, stable backport potential

#1421 MES Factory gradient support
  qiskit/chemistry/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uccsd_factory.py
  qiskit/chemistry/algorithms/ground_state_solvers/minimum_eigensolver_factories/vqe_uvccsd_factory.py
Labels: Changelog: New Feature, Chemistry

#1430 Change vibronic result to solve deprecation warning
  qiskit/chemistry/results/vibronic_structure_result.py
Labels: Changelog: Bugfix

#1442 Fix Chemistry python 3.8 CI fail on unit test load due to pyquante
  .github/workflows/main.yml
Labels: stable backport potential

#1445 Sort variational parameters by name in Quantum Generator
  qiskit/aqua/components/neural_networks/quantum_generator.py
  releasenotes/notes/sort-quantum-generator-params-4b358df0fe1cf3f7.yaml
Labels: Changelog: Bugfix

#1407 Fix propagation of grad_combo_fn
  qiskit/aqua/operators/list_ops/list_op.py
  releasenotes/notes/grad-combo-fn-propagation-6f7c442a5ef977b8.yaml
Labels: Changelog: Bugfix

#1447 Fix CircuitSampler paramerter bindings on ListOp with differing parameters and small updates
  qiskit/aqua/operators/converters/circuit_sampler.py
  qiskit/aqua/operators/gradients/natural_gradient.py
  releasenotes/notes/fix-circuitsampler-bindings-for-listop-5f98df655b3151e4.yaml
  test/aqua/operators/test_state_op_meas_evals.py
Labels: Changelog: Bugfix

#1404 Port RawFeatureVector to a circuit
  docs/apidocs/qiskit.ml.circuit.library.rst
  qiskit/aqua/algorithms/classifiers/qsvm/qsvm.py
  qiskit/aqua/algorithms/classifiers/vqc.py
  qiskit/aqua/circuits/statevector_circuit.py
  qiskit/aqua/components/feature_maps/feature_map.py
  qiskit/aqua/components/feature_maps/raw_feature_vector.py
  qiskit/chemistry/circuit/__init__.py
  qiskit/chemistry/circuit/library/initial_states/hartree_fock.py
  qiskit/ml/__init__.py
  qiskit/ml/circuit/__init__.py
  qiskit/ml/circuit/library/__init__.py
  qiskit/ml/circuit/library/raw_feature_vector.py
  releasenotes/notes/raw-feature-circuit-c1cb26f0189d03fb.yaml
  requirements-dev.txt
  test/aqua/test_vqc.py
  test/ml/circuit/library/test_raw_feature_vector.py
Labels: Changelog: Deprecation, Changelog: New Feature

#1196 Change QuadraticProgramConverter.interpret to convert `x` directly
  qiskit/optimization/algorithms/admm_optimizer.py
  qiskit/optimization/algorithms/cplex_optimizer.py
  qiskit/optimization/algorithms/grover_optimizer.py
  qiskit/optimization/algorithms/minimum_eigen_optimizer.py
  qiskit/optimization/algorithms/optimization_algorithm.py
  qiskit/optimization/algorithms/recursive_minimum_eigen_optimizer.py
  qiskit/optimization/converters/__init__.py
  qiskit/optimization/converters/inequality_to_equality.py
  qiskit/optimization/converters/integer_to_binary.py
  qiskit/optimization/converters/ising_to_quadratic_program.py
  qiskit/optimization/converters/linear_equality_to_penalty.py
  qiskit/optimization/converters/quadratic_program_converter.py
  qiskit/optimization/converters/quadratic_program_to_ising.py
  qiskit/optimization/converters/quadratic_program_to_qubo.py
  releasenotes/notes/refactor_interpret-1d35f44d08d87e2c.yaml
  test/optimization/test_converters.py
  test/optimization/test_min_eigen_optimizer.py
Labels: Changelog: API Change, Changelog: Deprecation, Optimization
