Repository Qiskit/qiskit-aqua, pull requests merged in 2020-07, with the labels that each got.

#1085 OperatorStateFn: bind parameters in coeff and primitive
  qiskit/aqua/operators/state_fns/state_fn.py
  releasenotes/notes/param-binding-opstatefn-44d6a3719c20263c.yaml
  test/aqua/operators/test_state_construction.py
Labels: Changelog: Bugfix, stable backport potential

#1094 CircuitStateFn.assign_parameters overwrites is_measurement
  qiskit/aqua/operators/state_fns/circuit_state_fn.py
  releasenotes/notes/circs-bind-loses-meas-b11deaceefcf2178.yaml
Labels: Changelog: Bugfix

#1059 SummedOp updates & optimization converters to use Opflow
  qiskit/aqua/operators/list_ops/summed_op.py
  qiskit/aqua/operators/primitive_ops/pauli_op.py
  qiskit/aqua/operators/primitive_ops/primitive_op.py
  qiskit/optimization/converters/ising_to_quadratic_program.py
  qiskit/optimization/converters/quadratic_program_to_ising.py
  releasenotes/notes/summed-op-compare-3df17046849af9a8.yaml
  test/aqua/operators/test_op_construction.py
  test/optimization/test_converters.py
  test/optimization/test_docplex.py
  test/optimization/test_qaoa.py
Labels: Changelog: New Feature

#1117 Fix to accommodate latest docplex 2.15.194
  qiskit/optimization/problems/quadratic_expression.py
  qiskit/optimization/problems/quadratic_program.py
Labels: stable backport potential

#1115 Fix qgan.py where batch size is greater than data size to raise error
  qiskit/aqua/algorithms/distribution_learners/qgan.py
Labels: Changelog: Bugfix, stable backport potential

#1110 For Z2Symmetry, chop resultant tapered operators
  qiskit/chemistry/core/hamiltonian.py
Labels: Changelog: Bugfix, stable backport potential

#1123 P_BFGS spawn crash on MacOS and python >= 3.8
  qiskit/aqua/components/optimizers/p_bfgs.py
  releasenotes/notes/P_BFGS-MacOS-4013becffcdf435a.yaml
Labels: Changelog: Bugfix

#1128 Determine the max number of ancillae for all ESOPs (TruthTableOracle fix)
  qiskit/aqua/circuits/boolean_logical_circuits.py
  qiskit/aqua/components/oracles/truth_table_oracle.py
Labels: Changelog: Bugfix

#1111 Matrix multiplicative factor (z + z == 2 * z)
  qiskit/aqua/operators/primitive_ops/matrix_op.py
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix, stable backport potential

#1105 Check number of qubits in PauliOp.eval
  qiskit/aqua/operators/primitive_ops/pauli_op.py
  releasenotes/notes/pauli-op-check-num-qubits-ab1a88ff3436b495.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix

#1140 Make pyscf an optional dependency
  .travis.yml
  README.md
  qiskit/chemistry/drivers/__init__.py
  qiskit/chemistry/drivers/pyscfd/__init__.py
  requirements.txt
  setup.py
  test/chemistry/test_driver_fcidump_dumper.py
Labels: stable backport potential

#1146 Fix torch abstract class method not implemented
  .pylintdict
  .travis.yml
  qiskit/aqua/components/neural_networks/_pytorch_discriminator_net.py
Labels: stable backport potential

#1152 Fix preservation of ListOp's combofn
  qiskit/aqua/operators/list_ops/list_op.py
  releasenotes/notes/listop-combofn-ce0be39602f778a1.yaml
  test/aqua/operators/test_op_construction.py
Labels: Changelog: Bugfix
