Repository Qiskit/qiskit-aqua, pull requests merged in 2021-03, with the labels that each got.

#1549 Changes due to Terra QFT Little endian
  qiskit/aqua/algorithms/amplitude_estimators/ae.py
  qiskit/aqua/algorithms/factorizers/shor.py
  qiskit/aqua/circuits/phase_estimation_circuit.py
  qiskit/ml/circuit/library/raw_feature_vector.py
  test/aqua/test_amplitude_estimation.py
  test/aqua/test_amplitude_estimation_circuitfactory.py
  test/aqua/test_hhl.py
  test/aqua/test_qpe.py
  test/chemistry/test_end2end_with_qpe.py
Labels: priority: critical, type: bug

#1548 Pin dependent versions. Add to CI: cron job and support for env QISKIT_TESTS=run_slow
  .github/actions/install-aqua/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  constraints.txt
  requirements-dev.txt
  requirements.txt
  setup.py
  test/ml/circuit/__init__.py
  test/ml/circuit/library/__init__.py
Labels: type: enhancement

#1555 Bug fix for functions for stable set problems
  qiskit/optimization/applications/ising/stable_set.py
  test/optimization/test_stable_set.py
Labels: Changelog: Bugfix

#1554 Stop using basic aer internal private attributes
  qiskit/aqua/utils/run_circuits.py
Labels: priority: high

#1557 Extend version requirement for scipy
  requirements.txt
Labels: priority: high, type: bug
