Repository Qiskit/qiskit-aqua, pull requests merged in 2021-04, with the labels that each got.

#1569 Move release notes to 0.9 folder
  releasenotes/notes/0.9/QSVM-L2-Norm-3382893ecafee124.yaml
  releasenotes/notes/0.9/add-python3.9-aa545158de52b755.yaml
  releasenotes/notes/0.9/aqgd-int-values-fix-9d9c74381802be18.yaml
  releasenotes/notes/0.9/batch-opt-var-generation-63d308b550972f9b.yaml
  releasenotes/notes/0.9/change-vqc-loss-handle-8a83c292f74609c9.yaml
  releasenotes/notes/0.9/deprecate-initial-states-61cd9f2842971ccb.yaml
  releasenotes/notes/0.9/docplex-fix-e401d4b511ca5244.yaml
  releasenotes/notes/0.9/fix-circuitsampler-bindings-for-listop-5f98df655b3151e4.yaml
  releasenotes/notes/0.9/fix-grover-opt-assertions-e2d8a5ff570134a1.yaml
  releasenotes/notes/0.9/fix-operator-flow-33a0bd315151562c.yaml
  releasenotes/notes/0.9/fix_hashable-0ccf249a2c19fc0e.yaml
  releasenotes/notes/0.9/grad-combo-fn-propagation-6f7c442a5ef977b8.yaml
  releasenotes/notes/0.9/grad_chain_rule_fix-b167d35e94ac8224.yaml
  releasenotes/notes/0.9/interpret-samples-da97b2b39a249592.yaml
  releasenotes/notes/0.9/nat_grad_generic_loss-787bd4ef38b28261.yaml
  releasenotes/notes/0.9/noise_model-8e27eb648456f8a9.yaml
  releasenotes/notes/0.9/pass_manager-c5e934ffc31addb0.yaml
  releasenotes/notes/0.9/qaoa-initial-state-bugfix-a92b38b805f36209.yaml
  releasenotes/notes/0.9/qi-seed-simulator-757f88ec183082f7.yaml
  releasenotes/notes/0.9/quantum-generator-analytic-gradients-a1be50818527170c.yaml
  releasenotes/notes/0.9/quantum-generator-optimizer-bdaa7a20f9f393b3.yaml
  releasenotes/notes/0.9/raw-feature-circuit-c1cb26f0189d03fb.yaml
  releasenotes/notes/0.9/refactor_interpret-1d35f44d08d87e2c.yaml
  releasenotes/notes/0.9/slice-inheritance-support-ListOp-9ffb59361457db25.yaml
  releasenotes/notes/0.9/slice-support-ListOp-ea586438661d2ca9.yaml
  releasenotes/notes/0.9/sort-quantum-generator-params-4b358df0fe1cf3f7.yaml
  releasenotes/notes/0.9/time_taken-51921da97ca3c13a.yaml
Labels: stable backport potential

#1566 Fix migration guide for aqua_globals
  README.md
  qiskit/aqua/aqua_globals.py
Labels: stable backport potential

#1572 Improve migration guide
  docs/tutorials/Qiskit Algorithms Migration Guide.ipynb
Labels: stable backport potential

#1575 Disable Conan on CI Aer build
  .github/actions/install-master-dependencies/action.yml
Labels: priority: high, stable backport potential, type: bug

#1579 Fix syntax error on CI
  .github/workflows/main.yml
Labels: stable backport potential, type: bug

#1580 [Stable] Fix syntax error on CI (#1579)
  .github/workflows/main.yml
Labels: type: bug

#1584 Prepare for renaming default branch to main
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/tutorials/Qiskit Algorithms Migration Guide.ipynb
  qiskit/aqua/deprecation.py
  qiskit/aqua/version.py
  qiskit/chemistry/drivers/gaussiand/__init__.py
  tox.ini
Labels: stable backport potential

#1588 Fix lint msgs caused by latest pylint release
  qiskit/aqua/components/reciprocals/long_division.py
  qiskit/aqua/version.py
  qiskit/chemistry/drivers/gaussiand/gaussian_utils.py
  qiskit/chemistry/drivers/psi4d/psi4driver.py
  test/chemistry/test_driver_fcidump_dumper.py
  test/optimization/test_quadratic_program.py
  tools/check_copyright.py
Labels: priority: high, stable backport potential, type: bug
