Repository Qiskit/qiskit-aqua, pull requests merged in 2021-06, with the labels that each got.

#1599 Add deprecation msg to issues/PR templates & docs
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  docs/apidocs/aqua.rst
Labels: type: documentation

#1601 CI Run Qiskit Tutorials against stable branch
  .github/workflows/main.yml
Labels: stable backport potential, type: ci

#1603 Pin mypy to < 0.900
  requirements-dev.txt
  requirements.txt
Labels: priority: critical, stable backport potential, type: bug

#1604 [Stable] Pin mypy to < 0.900 (#1603)
  requirements-dev.txt
  requirements.txt
Labels: type: bug

#1605 Remove overly aggresive pinning from requirements
  requirements.txt
Labels: priority: critical, stable backport potential

#1608 Add deprecation msg when importing aqua
  qiskit/aqua/__init__.py
  test/optimization/test_quadratic_program.py
Labels: stable backport potential, type: enhancement

#1611 Adjust unit test decimal places comparison
  qiskit/aqua/algorithms/linear_solvers/hhl.py
  qiskit/aqua/aqua_globals.py
  qiskit/aqua/components/optimizers/aqgd.py
  qiskit/aqua/operators/gradients/circuit_gradients/param_shift.py
  qiskit/chemistry/algorithms/excited_states_solvers/qeom.py
  qiskit/chemistry/algorithms/pes_samplers/potentials/harmonic_potential.py
  qiskit/chemistry/components/bosonic_bases/harmonic_basis.py
  qiskit/chemistry/drivers/fcidumpd/dumper.py
  qiskit/chemistry/drivers/fcidumpd/parser.py
  qiskit/optimization/algorithms/admm_optimizer.py
  requirements.txt
  test/aqua/test_amplitude_estimation.py
  test/aqua/test_amplitude_estimation_circuitfactory.py
Labels: stable backport potential, type: bug

#1612 [Stable] Adjust unit test decimal places comparison (#1611)
  qiskit/aqua/algorithms/linear_solvers/hhl.py
  qiskit/aqua/aqua_globals.py
  qiskit/aqua/components/optimizers/aqgd.py
  qiskit/aqua/operators/gradients/circuit_gradients/param_shift.py
  qiskit/chemistry/algorithms/excited_states_solvers/qeom.py
  qiskit/chemistry/algorithms/pes_samplers/potentials/harmonic_potential.py
  qiskit/chemistry/components/bosonic_bases/harmonic_basis.py
  qiskit/chemistry/drivers/fcidumpd/dumper.py
  qiskit/chemistry/drivers/fcidumpd/parser.py
  qiskit/optimization/algorithms/admm_optimizer.py
  requirements.txt
  test/aqua/test_amplitude_estimation.py
  test/aqua/test_amplitude_estimation_circuitfactory.py
Labels: type: bug

#1613 Adds 'aer_simulator_statevector' to QuantumInstance statevector check
  qiskit/aqua/utils/backend_utils.py
  releasenotes/notes/statevector-9d559b850cc32cb4.yaml
Labels: Changelog: Bugfix, stable backport potential

#1614 [Stable] Adds 'aer_simulator_statevector' to QuantumInstance statevector check (#1613)
  qiskit/aqua/utils/backend_utils.py
  releasenotes/notes/statevector-9d559b850cc32cb4.yaml
Labels: Changelog: Bugfix

#1615 Fix pylint errors
  constraints.txt
  qiskit/aqua/components/uncertainty_models/uncertainty_model.py
  qiskit/aqua/components/uncertainty_problems/multivariate_problem.py
  qiskit/aqua/operators/legacy/weighted_pauli_operator.py
  qiskit/aqua/utils/run_circuits.py
  qiskit/chemistry/bosonic_operator.py
  qiskit/chemistry/components/variational_forms/uccsd.py
  qiskit/chemistry/drivers/fcidumpd/fcidumpdriver.py
  qiskit/chemistry/results/vibronic_structure_result.py
  requirements-dev.txt
  test/aqua/operators/test_pauli_basis_change.py
  test/chemistry/test_bosonic_esc_calculation.py
  test/chemistry/test_excited_states_solvers.py
Labels: stable backport potential
